/**
 * SubmissionPort — graph-only persistence for submission lifecycle.
 * IDs are generated by the caller (CLI/use-case).
 */
export interface SubmissionPort {
  submit(args: {
    questId: string;
    submissionId: string;
    patchsetId: string;
    patchset: {
      workspaceRef: string;
      baseRef?: string;
      headRef?: string;
      commitShas?: string[];
      description: string;
    };
  }): Promise<{ patchSha: string }>;

  revise(args: {
    submissionId: string;
    patchsetId: string;
    supersedesPatchsetId: string;
    patchset: {
      workspaceRef: string;
      baseRef?: string;
      headRef?: string;
      commitShas?: string[];
      description: string;
    };
  }): Promise<{ patchSha: string }>;

  review(args: {
    patchsetId: string;
    reviewId: string;
    verdict: 'approve' | 'request-changes' | 'comment';
    comment: string;
  }): Promise<{ patchSha: string }>;

  decide(args: {
    submissionId: string;
    decisionId: string;
    kind: 'merge' | 'close';
    rationale: string;
    mergeCommit?: string;
  }): Promise<{ patchSha: string }>;
}
